export const pricingCards = [
  {
    title: "Starter",
    description: "Pour démarrer votre entreprise",
    price: "Gratuit",
    duration: "",
    highlight: "Fonctionnalités clés",
    features: ["1 Unité", "4 Membres", "Gestion de base des projets"],
    priceId: "starter",
  },
  {
    title: "Pro",
    description: "Pour les entreprises en croissance",
    price: "3500 DA",
    duration: "mois",
    highlight: "Tout dans Starter, plus",
    features: [
      "5 Unités",
      "20 Membres",
      "Support prioritaire",
      "Gestion avancée des projets",
    ],
    priceId: "pro",
  },
  {
    title: "Premium",
    description: "Pour les grandes entreprises",
    price: "7500 DA",
    duration: "mois",
    highlight: "Tout dans Pro, plus",
    features: [
      "Unités illimitées",
      "Membres illimités",
      "Support 24/7",
      "Analytics avancés",
      "Personnalisation complète",
    ],
    priceId: "premium",
  },
];

export const wilayas = [
  "1-Adrar",
  "2-Chlef",
  "3-Laghouat",
  "4-Oum El Bouaghi",
  "5-Batna",
  "6-Bejaia",
  "7-Biskra",
  "8-Bechar",
  "9-Blida",
  "10-Bouira",
  "11-Tamanrasset",
  "12-Tebessa",
  "13-Tlemcen",
  "14-Tiaret",
  "15-Tizi Ouzou",
  "16-Alger",
  "17-Djelfa",
  "18-Jijel",
  "19-Setif",
  "20-Saida",
  "21-Skikda",
  "22-Sidi Bel Abbes",
  "23-Annaba",
  "24-Guelma",
  "25-Constantine",
  "26-Medea",
  "27-Mostaganem",
  "28-MSila",
  "29-Mascara",
  "30-Ouargla",
  "31-Oran",
  "32-El Bayadh",
  "33-Illizi",
  "34-Bordj Bou Arreridj",
  "35-Boumerdes",
  "36-El Tarf",
  "37-Tindouf",
  "38-Tissemsilt",
  "39-El Oued",
  "40-Khenchela",
  "41-Souk Ahras",
  "42-Tipaza",
  "43-Mila",
  "44-Ain Defla",
  "45-Naama",
  "46-Ain Temouchent",
  "47-Ghardaia",
  "48-Relizane",
];
